# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b89e8d645defdda982d60fdf725658373b2799d52412e900a2d4addd54b648be60d324ae525430bb6039e68abbbd1e2101f7ebd48085d19ca1227187c3a0184

test:
  secret_key_base: 384fbe25a5155fe2e23aa0c7d8e932764cd30d3cb2372f653b58ca1b504c11c937401e9a68f36cb0047009f25ca96e17e9edc094b0c7753cc473af57b67d4ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
